import * as React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { HourlyHeatMap } from '~/components/CustomHeatmap/HourlyHeatMap';
import { MonthlyHeatMap } from '~/components/CustomHeatmap/MonthlyHeatMap';
import { hourlyData, monthlyData } from '~/components/data';
const IndexPage: NextPage = () => {
  return (
    <div className="flex justify-center">
      <div className="max-w-7xl">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="">
          <div className=" ">
            <HourlyHeatMap data={hourlyData} height={200} width={700} />
          </div>
          <MonthlyHeatMap data={monthlyData} height={200} width={700} />
        </div>
      </div>
    </div>
  );
};

export default IndexPage;
